name: ${project.artifactId}
main: com.jaoafa.PeriodMatch2.Main
version: 2020.05.01_18.09
description: jao Minecraft Serverでよく使用される「.」を使った対決がいまここに…！
database: true
author: mine_book000
softdepend: [TitleAPI]
website: https://jaoafa.com/
commands:
  .:
    description: ピリオド対決を行います
    usage: /<command>
    permission: periodmatch.period
    permission-message: You do not have permission to perform this command.
  periodmatch2:
    description: PeriodMatch2のリリース情報を表示します。
    usage: /<command>
    permission: periodmatch.periodmatch2
    permission-message: You do not have permission to perform this command.
