name: ${project.artifactId}
main: com.jaoafa.PeriodMatch2.Main
version: 2020.04.03_17.26
description: jao Minecraft Serverでよく使用される「.」を使った対決がいまここに…！
database: true
author: mine_book000
softdepend: [TitleAPI]
website: https://jaoafa.com/
commands:
  .:
    description: ピリオド対決を行います
    usage: /<command>
    permission: periodmatch.period
    permission-message: You do not have permission to perform this command.
